#!/usr/bin/env python3
"""
WAF Detector - Detects Web Application Firewalls across a list of domains.
Outputs a detailed report with signals found and confidence score per domain.

Usage:
    python3 waf_detector.py -d example.com cloudflare.com
    python3 waf_detector.py -f domains.txt
    python3 waf_detector.py -f domains.txt -o report.txt
"""

import argparse
import sys
import time
import random
import json
from datetime import datetime
from urllib.parse import urlparse
from typing import List, Dict, Optional


try:
    import requests
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
except ImportError:
    print("[!] 'requests' library not found. Install it with: pip3 install requests")
    sys.exit(1)

# ─────────────────────────────────────────────
# WAF FINGERPRINT DATABASE
# ─────────────────────────────────────────────

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "cf-edge-cache"],
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
        "server_values": ["cloudflare"],
        "body_keywords": ["cloudflare", "attention required", "cf-error-details", "ray id"],
        "block_page_indicators": ["cloudflare ray id", "error 1010", "error 1012", "error 1020"],
    },
    "Imperva (Incapsula)": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["visid_incap_", "incap_ses_", "nlbi_"],
        "server_values": ["incapsula"],
        "body_keywords": ["incapsula", "imperva", "request unsuccessful", "_Incapsula_Resource"],
        "block_page_indicators": ["incapsula incident id", "request blocked by incapsula"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "akamai-origin-hop", "x-check-cacheable", "x-akamai-request-id"],
        "cookies": ["ak_bmsc", "bm_sz", "bm_sv"],
        "server_values": ["akamaighost", "akamai"],
        "body_keywords": ["akamai", "reference #", "access denied"],
        "block_page_indicators": ["akamai technologies", "you don't have permission"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache", "x-sucuri-block"],
        "cookies": ["sucuri_cloudproxy_uuid"],
        "server_values": ["sucuri/cloudproxy"],
        "body_keywords": ["sucuri", "cloudproxy", "website firewall", "blocked by sucuri"],
        "block_page_indicators": ["sucuri website firewall", "access denied - sucuri"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amz-cf-pop"],
        "cookies": ["aws-waf-token"],
        "server_values": ["awselb", "amazon"],
        "body_keywords": ["aws waf", "request blocked", "403 forbidden"],
        "block_page_indicators": ["aws waf could not forward", "forbidden"],
    },
    "F5 BIG-IP": {
        "headers": ["x-wa-info", "x-cnection"],
        "cookies": ["bigipserver", "f5_cspm", "ts"],
        "server_values": ["big-ip", "f5"],
        "body_keywords": ["f5 networks", "the requested url was rejected", "bigip"],
        "block_page_indicators": ["the requested url was rejected", "please consult with your administrator"],
    },
    "Barracuda": {
        "headers": ["x-barracuda-connect", "x-barracuda-start-time"],
        "cookies": ["barra_counter_session", "BNI__BARRACUDA_LB_COOKIE"],
        "server_values": ["barracuda"],
        "body_keywords": ["barracuda", "barracuda networks", "you have been blocked"],
        "block_page_indicators": ["barracuda web application firewall"],
    },
    "Fortinet FortiWeb": {
        "headers": ["x-requestid"],
        "cookies": ["FORTIWAFSID", "cookiesession1"],
        "server_values": ["fortiweb", "fortigate"],
        "body_keywords": ["fortigate", "fortiweb", "application firewall -- url block"],
        "block_page_indicators": ["fortigate application control", "url block"],
    },
    "ModSecurity": {
        "headers": ["x-mod-security", "x-modsec"],
        "cookies": [],
        "server_values": ["mod_security", "modsecurity"],
        "body_keywords": ["mod_security", "modsecurity", "not acceptable", "this error was generated by mod_security"],
        "block_page_indicators": ["406 not acceptable", "mod_security"],
    },
    "Wordfence": {
        "headers": [],
        "cookies": ["wfvt_", "wordfence_verifiedHuman"],
        "server_values": [],
        "body_keywords": ["wordfence", "generated by wordfence", "your access to this site has been limited"],
        "block_page_indicators": ["generated by wordfence", "wordfence security"],
    },
    "Nginx (custom WAF)": {
        "headers": ["x-nginx-cache"],
        "cookies": [],
        "server_values": ["nginx"],
        "body_keywords": ["nginx", "access denied", "403 forbidden"],
        "block_page_indicators": [],
    },
}

# Payloads that should trigger WAF if present
MALICIOUS_PAYLOADS = [
    "/?q=<script>alert(1)</script>",
    "/?id=1' OR '1'='1",
    "/?file=../../../../etc/passwd",
    "/?cmd=;ls -la",
    "/?q=<img src=x onerror=alert(1)>",
]

BENIGN_PATH = "/"

HEADERS_NORMAL = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Connection": "close",
}


# ─────────────────────────────────────────────
# HELPER FUNCTIONS
# ─────────────────────────────────────────────

def normalize_url(domain: str) -> str:
    if not domain.startswith(("http://", "https://")):
        domain = "https://" + domain
    return domain.rstrip("/")


def safe_get(url: str, timeout: int = 10, allow_redirects: bool = True) -> Optional[requests.Response]:
    try:
        resp = requests.get(
            url,
            headers=HEADERS_NORMAL,
            timeout=timeout,
            verify=False,
            allow_redirects=allow_redirects,
        )
        return resp
    except requests.exceptions.SSLError:
        try:
            return requests.get(url.replace("https://", "http://"), headers=HEADERS_NORMAL, timeout=timeout, verify=False)
        except Exception:
            return None
    except Exception:
        return None


def check_headers(response_headers: dict) -> list[dict]:
    """Method 1: Check response headers for WAF fingerprints."""
    signals = []
    headers_lower = {k.lower(): v.lower() for k, v in response_headers.items()}

    for waf_name, sigs in WAF_SIGNATURES.items():
        for h in sigs["headers"]:
            if h.lower() in headers_lower:
                signals.append({
                    "method": "Header Detection",
                    "waf": waf_name,
                    "detail": f"Header '{h}' found with value: '{headers_lower[h.lower()][:80]}'",
                    "weight": 3,
                })

        # Check Server header
        server_val = headers_lower.get("server", "")
        for sv in sigs["server_values"]:
            if sv.lower() in server_val:
                signals.append({
                    "method": "Server Header",
                    "waf": waf_name,
                    "detail": f"Server header contains '{sv}': '{server_val[:80]}'",
                    "weight": 3,
                })

    # Generic suspicious headers
    suspicious = ["x-protected-by", "x-firewall", "x-waf", "x-security", "x-ddos-protection"]
    for h in suspicious:
        if h in headers_lower:
            signals.append({
                "method": "Header Detection",
                "waf": "Unknown WAF",
                "detail": f"Generic security header found: '{h}: {headers_lower[h][:80]}'",
                "weight": 1,
            })

    return signals


def check_cookies(response_headers: dict) -> list[dict]:
    """Method 2: Check cookies for WAF fingerprints."""
    signals = []
    set_cookie = response_headers.get("set-cookie", "") + response_headers.get("Set-Cookie", "")
    set_cookie_lower = set_cookie.lower()

    for waf_name, sigs in WAF_SIGNATURES.items():
        for cookie in sigs["cookies"]:
            if cookie.lower() in set_cookie_lower:
                signals.append({
                    "method": "Cookie Fingerprint",
                    "waf": waf_name,
                    "detail": f"WAF cookie '{cookie}' found in Set-Cookie header",
                    "weight": 3,
                })

    return signals


def check_response_codes(base_url: str) -> list[dict]:
    """Method 3: Send malicious payloads and compare response codes."""
    signals = []

    normal_resp = safe_get(base_url + BENIGN_PATH)
    if not normal_resp:
        return signals

    normal_code = normal_resp.status_code
    blocked_codes = []
    different_responses = 0

    for payload in MALICIOUS_PAYLOADS:
        time.sleep(random.uniform(0.3, 0.7))  # polite delay
        resp = safe_get(base_url + payload)
        if resp is None:
            signals.append({
                "method": "Response Code Analysis",
                "waf": "Unknown WAF",
                "detail": f"Connection reset/refused for payload: {payload} (possible WAF block)",
                "weight": 2,
            })
            different_responses += 1
            continue

        if resp.status_code in (403, 406, 429, 503, 301, 302) and resp.status_code != normal_code:
            blocked_codes.append((payload, resp.status_code))
            different_responses += 1

    if blocked_codes:
        for payload, code in blocked_codes:
            signals.append({
                "method": "Response Code Analysis",
                "waf": "Unknown WAF",
                "detail": f"HTTP {code} returned for malicious payload: {payload} (normal: {normal_code})",
                "weight": 2,
            })

    if different_responses >= 3:
        signals.append({
            "method": "Response Code Analysis",
            "waf": "Unknown WAF",
            "detail": f"Consistent blocking pattern: {different_responses}/{len(MALICIOUS_PAYLOADS)} payloads triggered different responses",
            "weight": 2,
        })

    return signals


def check_block_page(response_body: str, response_headers: dict) -> list[dict]:
    """Method 4: Inspect response body for WAF block page content."""
    signals = []
    body_lower = response_body.lower() if response_body else ""

    for waf_name, sigs in WAF_SIGNATURES.items():
        for keyword in sigs["body_keywords"]:
            if keyword.lower() in body_lower:
                signals.append({
                    "method": "Block Page Content",
                    "waf": waf_name,
                    "detail": f"Body contains WAF keyword: '{keyword}'",
                    "weight": 2,
                })
                break  # one match per WAF is enough for body

        for indicator in sigs["block_page_indicators"]:
            if indicator.lower() in body_lower:
                signals.append({
                    "method": "Block Page Content",
                    "waf": waf_name,
                    "detail": f"Block page indicator found: '{indicator}'",
                    "weight": 3,
                })

    return signals


def check_timing_behavior(base_url: str) -> list[dict]:
    """Method 5: Detect timing anomalies between clean and malicious requests."""
    signals = []

    times_normal = []
    times_malicious = []

    for _ in range(2):
        start = time.time()
        safe_get(base_url + BENIGN_PATH)
        times_normal.append(time.time() - start)
        time.sleep(0.3)

    for payload in MALICIOUS_PAYLOADS[:2]:
        start = time.time()
        safe_get(base_url + payload)
        times_malicious.append(time.time() - start)
        time.sleep(0.3)

    if times_normal and times_malicious:
        avg_normal = sum(times_normal) / len(times_normal)
        avg_malicious = sum(times_malicious) / len(times_malicious)
        diff = avg_malicious - avg_normal

        if diff > 1.5:
            signals.append({
                "method": "Timing Analysis",
                "waf": "Unknown WAF",
                "detail": f"Malicious requests significantly slower (+{diff:.2f}s avg) — possible deep inspection",
                "weight": 1,
            })
        elif diff < -0.5:
            signals.append({
                "method": "Timing Analysis",
                "waf": "Unknown WAF",
                "detail": f"Malicious requests faster by {abs(diff):.2f}s — possible early termination/block",
                "weight": 1,
            })

    return signals


# ─────────────────────────────────────────────
# CONFIDENCE SCORING
# ─────────────────────────────────────────────

def calculate_confidence(signals: list[dict]) -> tuple[int, str]:
    total_weight = sum(s["weight"] for s in signals)

    if total_weight == 0:
        return 0, "No WAF Detected"
    elif total_weight <= 2:
        return 25, "Low"
    elif total_weight <= 5:
        return 50, "Medium"
    elif total_weight <= 9:
        return 75, "High"
    else:
        return 95, "Very High"


def identify_waf(signals: list[dict]) -> str:
    waf_votes = {}
    for s in signals:
        waf = s["waf"]
        if waf != "Unknown WAF":
            waf_votes[waf] = waf_votes.get(waf, 0) + s["weight"]

    if not waf_votes:
        return "Unknown WAF" if signals else "None"

    return max(waf_votes, key=waf_votes.get)


# ─────────────────────────────────────────────
# MAIN SCANNER
# ─────────────────────────────────────────────

def scan_domain(domain: str) -> dict:
    base_url = normalize_url(domain)
    print(f"\n  [*] Scanning {base_url} ...")

    result = {
        "domain": domain,
        "url": base_url,
        "waf_detected": False,
        "waf_name": "None",
        "confidence_score": 0,
        "confidence_level": "No WAF Detected",
        "signals": [],
        "error": None,
    }

    # Initial request
    print(f"      → Method 1/5: Checking headers...")
    resp = safe_get(base_url)
    if resp is None:
        result["error"] = "Could not connect to domain"
        print(f"      ✗ Could not connect")
        return result

    # Method 1: Headers
    signals = check_headers(dict(resp.headers))

    # Method 2: Cookies
    print(f"      → Method 2/5: Checking cookies...")
    signals += check_cookies(dict(resp.headers))

    # Method 3: Response codes with payloads
    print(f"      → Method 3/5: Testing malicious payloads...")
    signals += check_response_codes(base_url)

    # Method 4: Block page body analysis (use malicious payload response)
    print(f"      → Method 4/5: Analyzing block page content...")
    mal_resp = safe_get(base_url + MALICIOUS_PAYLOADS[0])
    if mal_resp:
        signals += check_block_page(mal_resp.text, dict(mal_resp.headers))
        # Also check headers of malicious response
        signals += check_headers(dict(mal_resp.headers))
        signals += check_cookies(dict(mal_resp.headers))

    # Method 5: Timing
    print(f"      → Method 5/5: Timing behavior analysis...")
    signals += check_timing_behavior(base_url)

    # Deduplicate signals by detail
    seen = set()
    unique_signals = []
    for s in signals:
        key = s["detail"]
        if key not in seen:
            seen.add(key)
            unique_signals.append(s)

    score, level = calculate_confidence(unique_signals)
    waf_name = identify_waf(unique_signals)

    result["signals"] = unique_signals
    result["confidence_score"] = score
    result["confidence_level"] = level
    result["waf_detected"] = score > 0
    result["waf_name"] = waf_name

    status = f"✓ WAF Detected: {waf_name} (Confidence: {score}% - {level})" if score > 0 else "✓ No WAF detected"
    print(f"      {status}")

    return result


# ─────────────────────────────────────────────
# REPORT GENERATION
# ─────────────────────────────────────────────

def generate_report(results: List[Dict], output_file: Optional[str] = None) -> str:
    lines = []
    sep = "=" * 70

    lines.append(sep)
    lines.append("  WAF DETECTION REPORT")
    lines.append(f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"  Domains scanned: {len(results)}")
    lines.append(sep)

    # Summary table
    lines.append("\n  SUMMARY")
    lines.append("  " + "-" * 65)
    lines.append(f"  {'Domain':<35} {'WAF':<20} {'Confidence':<10} Score")
    lines.append("  " + "-" * 65)

    for r in results:
        if r["error"]:
            lines.append(f"  {r['domain']:<35} {'ERROR':<20} {'N/A':<10} -")
        else:
            lines.append(
                f"  {r['domain']:<35} {r['waf_name']:<20} {r['confidence_level']:<10} {r['confidence_score']}%"
            )
    lines.append("  " + "-" * 65)

    # Detailed findings
    lines.append("\n\n  DETAILED FINDINGS")
    lines.append("  " + "-" * 65)

    for r in results:
        lines.append(f"\n  ► {r['domain']}")
        lines.append(f"    URL         : {r['url']}")

        if r["error"]:
            lines.append(f"    Status      : ERROR — {r['error']}")
            continue

        lines.append(f"    WAF Detected: {'YES — ' + r['waf_name'] if r['waf_detected'] else 'NO'}")
        lines.append(f"    Confidence  : {r['confidence_score']}% ({r['confidence_level']})")
        lines.append(f"    Signals     : {len(r['signals'])} found")

        if r["signals"]:
            lines.append("")
            # Group by method
            by_method = {}
            for s in r["signals"]:
                by_method.setdefault(s["method"], []).append(s)

            for method, method_signals in by_method.items():
                lines.append(f"    [{method}]")
                for s in method_signals:
                    lines.append(f"      • [{s['waf']}] {s['detail']}")
        else:
            lines.append("    No WAF signals detected.")

        lines.append("")

    lines.append(sep)
    lines.append("  END OF REPORT")
    lines.append(sep)

    report = "\n".join(lines)

    if output_file:
        with open(output_file, "w") as f:
            f.write(report)
        print(f"\n  [+] Report saved to: {output_file}")

    return report


# ─────────────────────────────────────────────
# CLI ENTRY POINT
# ─────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="WAF Detector — Detect Web Application Firewalls across domains",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 waf_detector.py -d example.com
  python3 waf_detector.py -d cloudflare.com sucuri.net akamai.com
  python3 waf_detector.py -f domains.txt
  python3 waf_detector.py -f domains.txt -o report.txt
        """,
    )
    parser.add_argument("-d", "--domains", nargs="+", help="One or more domains to scan")
    parser.add_argument("-f", "--file", help="Text file with one domain per line")
    parser.add_argument("-o", "--output", help="Save report to this file (optional)")
    parser.add_argument("--json", action="store_true", help="Also output raw results as JSON")

    args = parser.parse_args()

    domains = []
    if args.domains:
        domains += args.domains
    if args.file:
        try:
            with open(args.file) as f:
                domains += [line.strip() for line in f if line.strip() and not line.startswith("#")]
        except FileNotFoundError:
            print(f"[!] File not found: {args.file}")
            sys.exit(1)

    if not domains:
        parser.print_help()
        sys.exit(1)

    domains = list(dict.fromkeys(domains))  # deduplicate, preserve order

    print(f"\n{'='*70}")
    print(f"  WAF DETECTOR — scanning {len(domains)} domain(s)")
    print(f"{'='*70}")

    results = []
    for domain in domains:
        result = scan_domain(domain)
        results.append(result)
        time.sleep(1)  # polite delay between domains

    report = generate_report(results, args.output)
    print("\n" + report)

    if args.json:
        json_file = (args.output or "waf_report").replace(".txt", "") + ".json"
        with open(json_file, "w") as f:
            json.dump(results, f, indent=2)
        print(f"\n  [+] JSON results saved to: {json_file}")


if __name__ == "__main__":
    main()
