




#!/usr/bin/env python3
"""
WAF Scanner - Paste your domains at the top, run, get a table + CSV report.
Install dependency first: pip3 install requests
"""

import csv
import time
import random
from datetime import datetime

try:
    import requests
    requests.packages.urllib3.disable_warnings()
except ImportError:
    print("[!] Run: pip3 install requests")
    raise SystemExit

# ─────────────────────────────────────────────────────────────────
# PASTE YOUR DOMAINS HERE
# Just copy the column from Excel and paste between the triple quotes.
# No formatting needed — one domain per line, exactly as copied.
# ─────────────────────────────────────────────────────────────────

DOMAINS_RAW = """
ionix.io
portal.ionix.io
www.ionix.io
demo.portal.ionix.io
go.ionix.io
www.cyberpion.com
go.cyberpion.com
em.ionix.io
partners.ionix.io
sl.ionix.io
info.ionix.io
sl.cyberpion.com
status.portal.ionix.io
"""

# ── do not edit below this line ──
DOMAINS = [line.strip() for line in DOMAINS_RAW.strip().splitlines() if line.strip() and not line.strip().startswith("#")]

# Output CSV filename
OUTPUT_CSV = "waf_report.csv"

# ─────────────────────────────────────────────────────────────────
# WAF SIGNATURES
# ─────────────────────────────────────────────────────────────────

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers":            ["cf-ray", "cf-cache-status", "cf-request-id", "cf-edge-cache"],
        "cookies":            ["__cfduid", "__cf_bm", "cf_clearance"],
        "server_values":      ["cloudflare"],
        "body_keywords":      ["cloudflare", "attention required", "cf-error-details", "ray id"],
        "block_indicators":   ["cloudflare ray id", "error 1010", "error 1012", "error 1020"],
    },
    "Imperva (Incapsula)": {
        "headers":            ["x-iinfo", "x-cdn"],
        "cookies":            ["visid_incap_", "incap_ses_", "nlbi_"],
        "server_values":      ["incapsula"],
        "body_keywords":      ["incapsula", "imperva", "request unsuccessful"],
        "block_indicators":   ["incapsula incident id", "request blocked by incapsula"],
    },
    "Akamai": {
        "headers":            ["x-akamai-transformed", "akamai-origin-hop", "x-akamai-request-id"],
        "cookies":            ["ak_bmsc", "bm_sz", "bm_sv"],
        "server_values":      ["akamaighost", "akamai"],
        "body_keywords":      ["akamai", "reference #"],
        "block_indicators":   ["akamai technologies", "you don't have permission"],
    },
    "Sucuri": {
        "headers":            ["x-sucuri-id", "x-sucuri-cache", "x-sucuri-block"],
        "cookies":            ["sucuri_cloudproxy_uuid"],
        "server_values":      ["sucuri/cloudproxy"],
        "body_keywords":      ["sucuri", "cloudproxy", "website firewall"],
        "block_indicators":   ["sucuri website firewall", "access denied - sucuri"],
    },
    "AWS WAF": {
        "headers":            ["x-amzn-requestid", "x-amz-cf-id", "x-amz-cf-pop"],
        "cookies":            ["aws-waf-token"],
        "server_values":      ["awselb", "amazon"],
        "body_keywords":      ["aws waf", "request blocked"],
        "block_indicators":   ["aws waf could not forward"],
    },
    "F5 BIG-IP": {
        "headers":            ["x-wa-info", "x-cnection"],
        "cookies":            ["bigipserver", "f5_cspm"],
        "server_values":      ["big-ip", "f5"],
        "body_keywords":      ["f5 networks", "the requested url was rejected"],
        "block_indicators":   ["the requested url was rejected"],
    },
    "Barracuda": {
        "headers":            ["x-barracuda-connect", "x-barracuda-start-time"],
        "cookies":            ["barra_counter_session", "BNI__BARRACUDA_LB_COOKIE"],
        "server_values":      ["barracuda"],
        "body_keywords":      ["barracuda networks", "you have been blocked"],
        "block_indicators":   ["barracuda web application firewall"],
    },
    "Fortinet FortiWeb": {
        "headers":            ["x-requestid"],
        "cookies":            ["FORTIWAFSID"],
        "server_values":      ["fortiweb", "fortigate"],
        "body_keywords":      ["fortigate", "fortiweb", "url block"],
        "block_indicators":   ["fortigate application control"],
    },
    "ModSecurity": {
        "headers":            ["x-mod-security", "x-modsec"],
        "cookies":            [],
        "server_values":      ["mod_security", "modsecurity"],
        "body_keywords":      ["mod_security", "modsecurity", "not acceptable"],
        "block_indicators":   ["406 not acceptable", "mod_security"],
    },
    "Wordfence": {
        "headers":            [],
        "cookies":            ["wfvt_", "wordfence_verifiedHuman"],
        "server_values":      [],
        "body_keywords":      ["wordfence", "generated by wordfence"],
        "block_indicators":   ["generated by wordfence", "wordfence security"],
    },
}

MALICIOUS_PAYLOADS = [
    "/?q=<script>alert(1)</script>",
    "/?id=1' OR '1'='1",
    "/?file=../../../../etc/passwd",
    "/?cmd=;ls -la",
]

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml;q=0.9,*/*;q=0.8",
    "Connection": "close",
}

# ─────────────────────────────────────────────────────────────────
# CORE DETECTION LOGIC
# ─────────────────────────────────────────────────────────────────

def normalize(domain):
    if not domain.startswith(("http://", "https://")):
        domain = "https://" + domain
    return domain.rstrip("/")


def fetch(url, timeout=10):
    try:
        return requests.get(url, headers=HEADERS, timeout=timeout, verify=False, allow_redirects=True)
    except Exception:
        try:
            return requests.get(url.replace("https://", "http://"), headers=HEADERS, timeout=timeout, verify=False)
        except Exception:
            return None


def detect_headers(resp_headers):
    signals = []
    h = {k.lower(): v.lower() for k, v in resp_headers.items()}
    for waf, sigs in WAF_SIGNATURES.items():
        for key in sigs["headers"]:
            if key.lower() in h:
                signals.append(("Header Detection", waf, 3))
        for sv in sigs["server_values"]:
            if sv.lower() in h.get("server", ""):
                signals.append(("Header Detection", waf, 3))
    generic = ["x-protected-by", "x-firewall", "x-waf", "x-security", "x-ddos-protection"]
    for g in generic:
        if g in h:
            signals.append(("Header Detection", "Unknown WAF", 1))
    return signals


def detect_cookies(resp_headers):
    signals = []
    cookies = resp_headers.get("set-cookie", "") + resp_headers.get("Set-Cookie", "")
    cl = cookies.lower()
    for waf, sigs in WAF_SIGNATURES.items():
        for c in sigs["cookies"]:
            if c.lower() in cl:
                signals.append(("Cookie Fingerprint", waf, 3))
    return signals


def detect_response_codes(base_url):
    signals = []
    normal = fetch(base_url + "/")
    if not normal:
        return signals
    normal_code = normal.status_code
    for payload in MALICIOUS_PAYLOADS:
        time.sleep(random.uniform(0.2, 0.5))
        r = fetch(base_url + payload)
        if r is None:
            signals.append(("Response Code Analysis", "Unknown WAF", 2))
        elif r.status_code in (403, 406, 429, 503) and r.status_code != normal_code:
            signals.append(("Response Code Analysis", "Unknown WAF", 2))
    return signals


def detect_block_page(base_url):
    signals = []
    r = fetch(base_url + MALICIOUS_PAYLOADS[0])
    if not r:
        return signals
    body = r.text.lower()
    for waf, sigs in WAF_SIGNATURES.items():
        for kw in sigs["body_keywords"]:
            if kw.lower() in body:
                signals.append(("Block Page Content", waf, 2))
                break
        for bi in sigs["block_indicators"]:
            if bi.lower() in body:
                signals.append(("Block Page Content", waf, 3))
    return signals


def detect_timing(base_url):
    signals = []
    times_normal, times_bad = [], []
    for _ in range(2):
        t = time.time(); fetch(base_url + "/"); times_normal.append(time.time() - t); time.sleep(0.3)
    for p in MALICIOUS_PAYLOADS[:2]:
        t = time.time(); fetch(base_url + p); times_bad.append(time.time() - t); time.sleep(0.3)
    if times_normal and times_bad:
        diff = (sum(times_bad) / len(times_bad)) - (sum(times_normal) / len(times_normal))
        if abs(diff) > 1.0:
            signals.append(("Timing Analysis", "Unknown WAF", 1))
    return signals


def confidence(total_weight, signal_count):
    if signal_count == 0:   return 0,  "No WAF Detected"
    elif signal_count == 1: return 50, "Medium"
    elif signal_count == 2: return 75, "High"
    else:                   return 95, "Very High"


def top_waf(signals):
    votes = {}
    for _, waf, weight in signals:
        if waf != "Unknown WAF":
            votes[waf] = votes.get(waf, 0) + weight
    return max(votes, key=votes.get) if votes else ("Unknown WAF" if signals else "None")


def scan(domain):
    base = normalize(domain)
    print(f"  Scanning {base} ...", end=" ", flush=True)

    r = fetch(base)
    if r is None:
        print("✗ unreachable")
        return {"domain": domain, "waf_detected": "Error", "waf_vendor": "N/A",
                "confidence": "N/A", "signals": "Connection failed"}

    all_signals = []
    all_signals += detect_headers(dict(r.headers))
    all_signals += detect_cookies(dict(r.headers))
    all_signals += detect_response_codes(base)
    all_signals += detect_block_page(base)
    all_signals += detect_timing(base)

    # Deduplicate
    seen, unique = set(), []
    for s in all_signals:
        key = (s[0], s[1])
        if key not in seen:
            seen.add(key)
            unique.append(s)

    total_weight  = sum(w for _, _, w in unique)
    signal_count  = len(set(m for m, _, _ in unique))
    score, level  = confidence(total_weight, signal_count)
    vendor         = top_waf(unique)
    methods_found  = sorted(set(m for m, _, _ in unique))

    print(f"{'WAF: ' + vendor if score > 0 else 'No WAF'} | {score}% {level}")

    return {
        "domain":        domain,
        "waf_detected":  "Yes" if score > 0 else "No",
        "waf_vendor":    vendor if score > 0 else "—",
        "confidence":    f"{score}% ({level})" if score > 0 else "—",
        "signals":       ", ".join(methods_found) if methods_found else "—",
    }


# ─────────────────────────────────────────────────────────────────
# PRINT TABLE
# ─────────────────────────────────────────────────────────────────

def print_table(results):
    COL = [38, 13, 22, 18, 55]
    headers = ["Domain/Subdomain", "WAF Detected", "WAF Vendor", "Confidence", "Signals Found"]
    sep = "+-" + "-+-".join("-" * c for c in COL) + "-+"
    def row(vals):
        return "| " + " | ".join(str(v).ljust(c) for v, c in zip(vals, COL)) + " |"

    print("\n" + sep)
    print(row(headers))
    print(sep)
    for r in results:
        print(row([r["domain"], r["waf_detected"], r["waf_vendor"], r["confidence"], r["signals"]]))
    print(sep)


# ─────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────

def main():
    print(f"\n{'='*60}")
    print(f"  WAF Scanner  |  {len(DOMAINS)} domains  |  {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"{'='*60}")

    results = []
    for domain in DOMAINS:
        results.append(scan(domain.strip()))
        time.sleep(0.5)

    # Print table
    print_table(results)

    # Save CSV
    fieldnames = ["domain", "waf_detected", "waf_vendor", "confidence", "signals"]
    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)

    print(f"\n  ✓ CSV saved to: {OUTPUT_CSV}\n")


if __name__ == "__main__":
    main()
